-- DDL COMMANDS: CREATE, RENAME, TRUNCATE, DROP 

-- TASKS:
-- 1. CREATE A DATABASE (CREATE)
-- 2. CREATE A TABLE USING VARIOUS DATATYPES (CREATE)
-- 3. INSERT VALUES IN THE THE TABLE (INSERT)
-- 4. REMOVE ALL TUPLES (TRUNCATE)
-- 5. DELETE THE ENTIRE TABLE (DROP)
-- 6. DELETE THE ENTIRE DATABASE (DROP)



-- SOLUTIONS:

-- 1. CREATE A DATABASE
CREATE DATABASE DATABASE_1;

USE DATABASE_1;


-- 2. CREATE A TABLE USING VARIOUS DATATYPES
CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INT NOT NULL UNIQUE PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    PHONE_NO INT UNIQUE,
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    JOINING_DATE DATETIME
);


-- 3. INSERT VALUES IN THE THE TABLE
INSERT INTO CUSTOMER
    (CUSTOMER_ID , FIRST_NAME , LAST_NAME , PHONE_NO , CITY , STATE , JOINING_DATE)
VALUES
    (001, 'SIDDHANT', 'KUMAR', 940012, 'JAMSHEDPUR', 'JHARKHAND', '2022-12-20 10:20:00' ),
    (002, 'ADITYA', 'GAUR', 842232, 'DELHI', 'DELHI', '2021-10-25 10:25:00'),
    (003, 'SHYAM', 'SUNDER', 782528, 'MUZAFFARPUR', 'BIHAR', '2020-09-22 05:24:00'),
    (004, 'SAMARTH', 'VERMA', 672628, 'GREATER NOIDA', 'UTTAR PRADESH', '2020-12-22 06:20:00'),
    (005, 'VARUN', 'SINGH', 922345, 'FARIDABAD', 'HARYANA', '2019-07-05 09:34:00');

SELECT *
FROM CUSTOMER;


-- 4. REMOVE ALL TUPLES
TRUNCATE TABLE CUSTOMER;


-- 5. DELETE THE ENTIRE TABLE
DROP TABLE IF EXISTS CUSTOMER;


-- 6. DELETE THE ENTIRE DATABASE
DROP DATABASE DATABASE_1;