-- SET OPERATIONS: UNION, INTERSECT, MINUS

-- TASKS:
-- 1. CREATE A DATABASE (CREATE)
-- 2. CREATE TWO TABLE USING VARIOUS DATATYPES (CREATE)
-- 3. INSERT VALUES IN BOTH THE TABLE (INSERT)
-- 4. PERFORM UNION OPERATION ON BOTH THE TABLE (UNION)
-- 5. PERFORM INTERSECT OPERATION ON BOTH THE TABLE (INTERSECT)
-- 6. PERFORM MINUS OPERATION ON BOTH THE TABLE (MINUS)


-- SOLUTIONS:

-- 1. CREATE A DATABASE
CREATE DATABASE DATABASE_2;

USE DATABASE_2;


-- 2. CREATE TWO TABLE USING VARIOUS DATATYPES
CREATE TABLE TABLE_1
(
    T_ID INT PRIMARY KEY UNIQUE NOT NULL,
    T_NAME VARCHAR(100)
);

CREATE TABLE TABLE_2
(
    T_ID INT PRIMARY KEY UNIQUE NOT NULL,
    T_NAME VARCHAR(100)
);


-- 3. INSERT VALUES IN BOTH THE TABLE
INSERT INTO TABLE_1
    (T_ID, T_NAME)
VALUES
    (1, 'SIDDHANT'),
    (2, 'VARUN'),
    (3, 'PRASANT'),
    (4, 'ADITYA'),
    (5, 'SAMARTH');

SELECT *
FROM TABLE_1;


INSERT INTO TABLE_2
    (T_ID, T_NAME)
VALUES
    (2, 'VARUN'),
    (4, 'ADITYA'),
    (7, 'SHYAM');

SELECT *
FROM TABLE_2;


-- 4. PERFORM UNION OPERATION ON BOTH THE TABLE
    SELECT *
    FROM TABLE_1
UNION
    SELECT *
    FROM TABLE_2;


-- 5. PERFORM INTERSECT OPERATION ON BOTH THE TABLE
SELECT DISTINCT *
FROM TABLE_1 INNER JOIN TABLE_2 USING (T_ID) ;


-- 6. PERFORM MINUS OPERATION ON BOTH THE TABLE
SELECT TABLE_1.*
FROM TABLE_1 LEFT JOIN TABLE_2 USING (T_ID) 
WHERE TABLE_2.T_ID IS NULL;