-- JOINS COMMANDS: INNER, LEFT, RIGHT, FULL OUTER

-- TASKS:
-- 1. CREATE A DATABASE (CREATE)
-- 2. CREATE TWO TABLE USING VARIOUS DATATYPES (CREATE)
-- 3. INSERT VALUES IN BOTH THE TABLE (INSERT)
-- 4. PERFORM INNER JOIN ON BOTH THE TABLE (INNER)
-- 5. PERFORM LEFT JOIN ON TABLE 1 WITH TABLE 2 (LEFT)
-- 6. PERFORM RIGHT JOIN ON TABLE 2 WITH TABLE 1 (RIGHT)
-- 7. PERFORM FULL OUTER JOIN ON BOTH THE TABLE (FULL OUTER)


-- SOLUTIONS:

-- 1. CREATE A DATABASE
CREATE DATABASE DATABASE_2;

USE DATABASE_2;


-- 2. CREATE TWO TABLE USING VARIOUS DATATYPES
CREATE TABLE TABLE_1
(
    MAIN1_ID INT PRIMARY KEY NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DATE_OF_BIRTH DATE
);

CREATE TABLE TABLE_2
(
    MAIN2_ID INT PRIMARY KEY NOT NULL UNIQUE,
    CLASS VARCHAR(100),
    EMAIL VARCHAR(100),
    JOINING_DATE DATETIME
);


-- 3. INSERT VALUES IN BOTH THE TABLE
INSERT INTO TABLE_1
    (MAIN1_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH)
VALUES
    (1, 'John', 'Doe', '1990-05-15'),
    (2, 'Jane', 'Smith', '1985-08-20'),
    (3, 'Robert', 'Johnson', '1992-03-10'),
    (4, 'Emily', 'Davis', '1988-11-25');

SELECT *
FROM TABLE_1;


INSERT INTO TABLE_2
    (MAIN2_ID, CLASS, EMAIL, JOINING_DATE)
VALUES
    (2, 'Math', 'math_teacher@example.com', '2022-01-15 09:30:00'),
    (4, 'History', 'history_teacher@example.com', '2022-02-10 10:15:00'),
    (5, 'Science', 'science_teacher@example.com', '2022-03-05 11:00:00');

SELECT *
FROM TABLE_2;


-- 4. PERFORM INNER JOIN ON BOTH THE TABLE
SELECT C1.*, C2.*
FROM TABLE_1 AS C1 INNER JOIN TABLE_2 AS C2 ON C1.MAIN1_ID = C2.MAIN2_ID;


-- 5. PERFORM LEFT JOIN ON TABLE 1 WITH TABLE 2
SELECT C1.*, C2.*
FROM TABLE_1 AS C1 LEFT JOIN TABLE_2 AS C2 ON C1.MAIN1_ID = C2.MAIN2_ID;


-- 6. PERFORM RIGHT JOIN ON TABLE 2 WITH TABLE 1
SELECT C1.*, C2.*
FROM TABLE_1 AS C1 RIGHT JOIN TABLE_2 AS C2 ON C1.MAIN1_ID = C2.MAIN2_ID;


-- 7. PERFORM FULL OUTER JOIN ON BOTH THE TABLE
    SELECT C1.*, C2.*
    FROM TABLE_1 AS C1 LEFT JOIN TABLE_2 AS C2 ON C1.MAIN1_ID = C2.MAIN2_ID
UNION
    SELECT C1.*, C2.*
    FROM TABLE_1 AS C1 RIGHT JOIN TABLE_2 AS C2 ON C1.MAIN1_ID = C2.MAIN2_ID;